name: Continuous deploy

on:
  push:
    branches: [main]

jobs:
  serverless-deploy:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
      AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Install dependencies
        run: yarn ci

      - name: Download `.serverless` state from S3
        run: aws s3 sync s3://you-transfer/serverless-test/prod/.serverless .serverless --delete

      - name: Deploy to AWS
        run: yarn run deploy

      - name: Upload `.serverless` state to S3
        run: aws s3 sync .serverless s3://you-transfer/serverless-test/prod/.serverless --delete
